name = "NestedGraphs"
uuid = "03c36417-ddab-428a-818d-5359aee292ef"
authors = ["fchrstou <filippos.christou@ikr.uni-stuttgart.de> and contributors"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"

[compat]
AbstractTrees = "0.4"
DocStringExtensions = "0.9"
Graphs = "1"
MetaGraphs = "0.7"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
